package model.pojo;
// Generated 06/07/2014 15:27:33 by Hibernate Tools 3.6.0

import java.util.Objects;




/**
 * Escalacao generated by hbm2java
 */
public class Escalacao  implements java.io.Serializable {


     private Integer id;
     private Selecao selecao;
     private Jogador jogador;
     private Jogo jogo;

    public Escalacao() {
    }

    public Escalacao(Selecao selecao, Jogador jogador, Jogo jogo) {
       this.selecao = selecao;
       this.jogador = jogador;
       this.jogo = jogo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }

        @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + Objects.hashCode(this.id);
        hash = 41 * hash + Objects.hashCode(this.selecao);
        hash = 41 * hash + Objects.hashCode(this.jogo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Escalacao other = (Escalacao) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.selecao.getId(), other.selecao.getId())) {
            return false;
        }
        if (!Objects.equals(this.jogo.getId(), other.jogo.getId())) {
            return false;
        }
        return true;
    }

}


