package model.pojo;
// Generated 12/06/2014 11:49:37 by Hibernate Tools 3.6.0



/**
 * Escalacao generated by hbm2java
 */
public class Escalacao  implements java.io.Serializable {


     private int id;

    public Escalacao() {
    }

    public Escalacao(int id) {
       this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Escalacao other = (Escalacao) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }




}


