package model.pojo;
// Generated 01/07/2014 08:14:24 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.Objects;

/**
 * Gol generated by hbm2java
 */
public class Gol  implements java.io.Serializable {


     private int id;
     private Jogador jogador;
     private Selecao selecao;
     private Jogo jogo;
     private Date tempo;
     private boolean foiContra;

    public Gol() {
    }

    public Gol(int id, Jogador jogador, Selecao selecao, Jogo jogo, Date tempo, boolean foiContra) {
       this.id = id;
       this.jogador = jogador;
       this.selecao = selecao;
       this.jogo = jogo;
       this.tempo = tempo;
       this.foiContra = foiContra;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Date getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Date tempo) {
        this.tempo = tempo;
    }
    public boolean isFoiContra() {
        return this.foiContra;
    }
    
    public void setFoiContra(boolean foiContra) {
        this.foiContra = foiContra;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + Objects.hashCode(this.jogador);
        hash = 83 * hash + Objects.hashCode(this.selecao);
        hash = 83 * hash + Objects.hashCode(this.jogo);
        hash = 83 * hash + Objects.hashCode(this.tempo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Gol other = (Gol) obj;
        if (!Objects.equals(this.jogador, other.jogador)) {
            return false;
        }
        if (!Objects.equals(this.selecao, other.selecao)) {
            return false;
        }
        if (!Objects.equals(this.jogo, other.jogo)) {
            return false;
        }
        if (!Objects.equals(this.tempo, other.tempo)) {
            return false;
        }
        return true;
    }




}


