package model.pojo;
// Generated 03/07/2014 09:33:32 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Gol generated by hbm2java
 */
public class Gol  implements java.io.Serializable {


     private Integer id;
     private Jogador jogador;
     private Selecao selecao;
     private Jogo jogo;
     private Date tempo;
     private boolean foiContra;
     private Set jogosForGolB = new HashSet(0);
     private Set jogosForGolA = new HashSet(0);

    public Gol() {
    }

	
    public Gol(Date tempo, boolean foiContra) {
        this.tempo = tempo;
        this.foiContra = foiContra;
    }
    public Gol(Jogador jogador, Selecao selecao, Jogo jogo, Date tempo, boolean foiContra, Set jogosForGolB, Set jogosForGolA) {
       this.jogador = jogador;
       this.selecao = selecao;
       this.jogo = jogo;
       this.tempo = tempo;
       this.foiContra = foiContra;
       this.jogosForGolB = jogosForGolB;
       this.jogosForGolA = jogosForGolA;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Date getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Date tempo) {
        this.tempo = tempo;
    }
    public boolean isFoiContra() {
        return this.foiContra;
    }
    
    public void setFoiContra(boolean foiContra) {
        this.foiContra = foiContra;
    }
    public Set getJogosForGolB() {
        return this.jogosForGolB;
    }
    
    public void setJogosForGolB(Set jogosForGolB) {
        this.jogosForGolB = jogosForGolB;
    }
    public Set getJogosForGolA() {
        return this.jogosForGolA;
    }
    
    public void setJogosForGolA(Set jogosForGolA) {
        this.jogosForGolA = jogosForGolA;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        hash = 97 * hash + Objects.hashCode(this.jogador);
        hash = 97 * hash + Objects.hashCode(this.jogo);
        hash = 97 * hash + Objects.hashCode(this.tempo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Gol other = (Gol) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.jogador, other.jogador)) {
            return false;
        }
        if (!Objects.equals(this.jogo, other.jogo)) {
            return false;
        }
        if (!Objects.equals(this.tempo, other.tempo)) {
            return false;
        }
        return true;
    }




}


