package model.pojo;
// Generated 30/06/2014 12:17:05 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Jogador generated by hbm2java
 */
public class Jogador  implements java.io.Serializable {


     private int id;
     private Date dataNascimento;
     private String nome;
     private int numero;
     private String posicao;
     private Set escalacaosForJogador3 = new HashSet(0);
     private Set escalacaosForJogador6 = new HashSet(0);
     private Set gols = new HashSet(0);
     private Set escalacaosForJogador7 = new HashSet(0);
     private Set escalacaosForJogador11 = new HashSet(0);
     private Set escalacaosForJogador4 = new HashSet(0);
     private Set escalacaosForJogador9 = new HashSet(0);
     private Set substituicaosForJogadorSai = new HashSet(0);
     private Set escalacaosForJogador8 = new HashSet(0);
     private Set substituicaosForJogadorEntra = new HashSet(0);
     private Set escalacaosForJogador5 = new HashSet(0);
     private Set escalacaosForJogador1 = new HashSet(0);
     private Set escalacaosForJogador2 = new HashSet(0);
     private Set escalacaosForJogador10 = new HashSet(0);

    public Jogador() {
    }

	
    public Jogador(int id, Date dataNascimento, String nome, int numero, String posicao) {
        this.id = id;
        this.dataNascimento = dataNascimento;
        this.nome = nome;
        this.numero = numero;
        this.posicao = posicao;
    }
    public Jogador(int id, Date dataNascimento, String nome, int numero, String posicao, Set escalacaosForJogador3, Set escalacaosForJogador6, Set gols, Set escalacaosForJogador7, Set escalacaosForJogador11, Set escalacaosForJogador4, Set escalacaosForJogador9, Set substituicaosForJogadorSai, Set escalacaosForJogador8, Set substituicaosForJogadorEntra, Set escalacaosForJogador5, Set escalacaosForJogador1, Set escalacaosForJogador2, Set escalacaosForJogador10) {
       this.id = id;
       this.dataNascimento = dataNascimento;
       this.nome = nome;
       this.numero = numero;
       this.posicao = posicao;
       this.escalacaosForJogador3 = escalacaosForJogador3;
       this.escalacaosForJogador6 = escalacaosForJogador6;
       this.gols = gols;
       this.escalacaosForJogador7 = escalacaosForJogador7;
       this.escalacaosForJogador11 = escalacaosForJogador11;
       this.escalacaosForJogador4 = escalacaosForJogador4;
       this.escalacaosForJogador9 = escalacaosForJogador9;
       this.substituicaosForJogadorSai = substituicaosForJogadorSai;
       this.escalacaosForJogador8 = escalacaosForJogador8;
       this.substituicaosForJogadorEntra = substituicaosForJogadorEntra;
       this.escalacaosForJogador5 = escalacaosForJogador5;
       this.escalacaosForJogador1 = escalacaosForJogador1;
       this.escalacaosForJogador2 = escalacaosForJogador2;
       this.escalacaosForJogador10 = escalacaosForJogador10;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }
    public Set getEscalacaosForJogador3() {
        return this.escalacaosForJogador3;
    }
    
    public void setEscalacaosForJogador3(Set escalacaosForJogador3) {
        this.escalacaosForJogador3 = escalacaosForJogador3;
    }
    public Set getEscalacaosForJogador6() {
        return this.escalacaosForJogador6;
    }
    
    public void setEscalacaosForJogador6(Set escalacaosForJogador6) {
        this.escalacaosForJogador6 = escalacaosForJogador6;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }
    public Set getEscalacaosForJogador7() {
        return this.escalacaosForJogador7;
    }
    
    public void setEscalacaosForJogador7(Set escalacaosForJogador7) {
        this.escalacaosForJogador7 = escalacaosForJogador7;
    }
    public Set getEscalacaosForJogador11() {
        return this.escalacaosForJogador11;
    }
    
    public void setEscalacaosForJogador11(Set escalacaosForJogador11) {
        this.escalacaosForJogador11 = escalacaosForJogador11;
    }
    public Set getEscalacaosForJogador4() {
        return this.escalacaosForJogador4;
    }
    
    public void setEscalacaosForJogador4(Set escalacaosForJogador4) {
        this.escalacaosForJogador4 = escalacaosForJogador4;
    }
    public Set getEscalacaosForJogador9() {
        return this.escalacaosForJogador9;
    }
    
    public void setEscalacaosForJogador9(Set escalacaosForJogador9) {
        this.escalacaosForJogador9 = escalacaosForJogador9;
    }
    public Set getSubstituicaosForJogadorSai() {
        return this.substituicaosForJogadorSai;
    }
    
    public void setSubstituicaosForJogadorSai(Set substituicaosForJogadorSai) {
        this.substituicaosForJogadorSai = substituicaosForJogadorSai;
    }
    public Set getEscalacaosForJogador8() {
        return this.escalacaosForJogador8;
    }
    
    public void setEscalacaosForJogador8(Set escalacaosForJogador8) {
        this.escalacaosForJogador8 = escalacaosForJogador8;
    }
    public Set getSubstituicaosForJogadorEntra() {
        return this.substituicaosForJogadorEntra;
    }
    
    public void setSubstituicaosForJogadorEntra(Set substituicaosForJogadorEntra) {
        this.substituicaosForJogadorEntra = substituicaosForJogadorEntra;
    }
    public Set getEscalacaosForJogador5() {
        return this.escalacaosForJogador5;
    }
    
    public void setEscalacaosForJogador5(Set escalacaosForJogador5) {
        this.escalacaosForJogador5 = escalacaosForJogador5;
    }
    public Set getEscalacaosForJogador1() {
        return this.escalacaosForJogador1;
    }
    
    public void setEscalacaosForJogador1(Set escalacaosForJogador1) {
        this.escalacaosForJogador1 = escalacaosForJogador1;
    }
    public Set getEscalacaosForJogador2() {
        return this.escalacaosForJogador2;
    }
    
    public void setEscalacaosForJogador2(Set escalacaosForJogador2) {
        this.escalacaosForJogador2 = escalacaosForJogador2;
    }
    public Set getEscalacaosForJogador10() {
        return this.escalacaosForJogador10;
    }
    
    public void setEscalacaosForJogador10(Set escalacaosForJogador10) {
        this.escalacaosForJogador10 = escalacaosForJogador10;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 11 * hash + Objects.hashCode(this.dataNascimento);
        hash = 11 * hash + Objects.hashCode(this.nome);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Jogador other = (Jogador) obj;
        if (!Objects.equals(this.dataNascimento, other.dataNascimento)) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        return true;
    }




}


