package model.pojo;
// Generated 06/07/2014 15:27:33 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Jogador generated by hbm2java
 */
public class Jogador  implements java.io.Serializable {


     private Integer id;
     private Selecao selecao;
     private Date dataNascimento;
     private String nome;
     private int numero;
     private String posicao;
     private Set gols = new HashSet(0);
     private Set escalacaos = new HashSet(0);
     private Set substituicaosForJogadorEntra = new HashSet(0);
     private Set substituicaosForJogadorSai = new HashSet(0);

    public Jogador() {
    }

	
    public Jogador(Date dataNascimento, String nome, int numero, String posicao) {
        this.dataNascimento = dataNascimento;
        this.nome = nome;
        this.numero = numero;
        this.posicao = posicao;
    }
    public Jogador(Selecao selecao, Date dataNascimento, String nome, int numero, String posicao, Set gols, Set escalacaos, Set substituicaosForJogadorEntra, Set substituicaosForJogadorSai) {
       this.selecao = selecao;
       this.dataNascimento = dataNascimento;
       this.nome = nome;
       this.numero = numero;
       this.posicao = posicao;
       this.gols = gols;
       this.escalacaos = escalacaos;
       this.substituicaosForJogadorEntra = substituicaosForJogadorEntra;
       this.substituicaosForJogadorSai = substituicaosForJogadorSai;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }
    public Set getEscalacaos() {
        return this.escalacaos;
    }
    
    public void setEscalacaos(Set escalacaos) {
        this.escalacaos = escalacaos;
    }
    public Set getSubstituicaosForJogadorEntra() {
        return this.substituicaosForJogadorEntra;
    }
    
    public void setSubstituicaosForJogadorEntra(Set substituicaosForJogadorEntra) {
        this.substituicaosForJogadorEntra = substituicaosForJogadorEntra;
    }
    public Set getSubstituicaosForJogadorSai() {
        return this.substituicaosForJogadorSai;
    }
    
    public void setSubstituicaosForJogadorSai(Set substituicaosForJogadorSai) {
        this.substituicaosForJogadorSai = substituicaosForJogadorSai;
    }

@Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        hash = 97 * hash + Objects.hashCode(this.dataNascimento);
        hash = 97 * hash + Objects.hashCode(this.nome);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Jogador other = (Jogador) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.dataNascimento, other.dataNascimento)) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return this.getPosicao() +" - "+ this.getNome();
    }
}


