package model.pojo;
// Generated 27/06/2014 16:47:37 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jogo generated by hbm2java
 */
public class Jogo  implements java.io.Serializable {


     private int id;
     private Copa copa;
     private Selecao selecaoBySelecaoB;
     private Selecao selecaoBySelecaoA;
     private Escalacao escalacaoByEscalacaoB;
     private Escalacao escalacaoByEscalacaoA;
     private Date data;
     private String local;
     private String fase;
     private Set substituicaos = new HashSet(0);
     private Set gols = new HashSet(0);

    public Jogo() {
    }

	
    public Jogo(int id, Copa copa, Selecao selecaoBySelecaoB, Selecao selecaoBySelecaoA, Escalacao escalacaoByEscalacaoB, Escalacao escalacaoByEscalacaoA, Date data, String local, String fase) {
        this.id = id;
        this.copa = copa;
        this.selecaoBySelecaoB = selecaoBySelecaoB;
        this.selecaoBySelecaoA = selecaoBySelecaoA;
        this.escalacaoByEscalacaoB = escalacaoByEscalacaoB;
        this.escalacaoByEscalacaoA = escalacaoByEscalacaoA;
        this.data = data;
        this.local = local;
        this.fase = fase;
    }
    public Jogo(int id, Copa copa, Selecao selecaoBySelecaoB, Selecao selecaoBySelecaoA, Escalacao escalacaoByEscalacaoB, Escalacao escalacaoByEscalacaoA, Date data, String local, String fase, Set substituicaos, Set gols) {
       this.id = id;
       this.copa = copa;
       this.selecaoBySelecaoB = selecaoBySelecaoB;
       this.selecaoBySelecaoA = selecaoBySelecaoA;
       this.escalacaoByEscalacaoB = escalacaoByEscalacaoB;
       this.escalacaoByEscalacaoA = escalacaoByEscalacaoA;
       this.data = data;
       this.local = local;
       this.fase = fase;
       this.substituicaos = substituicaos;
       this.gols = gols;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Copa getCopa() {
        return this.copa;
    }
    
    public void setCopa(Copa copa) {
        this.copa = copa;
    }
    public Selecao getSelecaoBySelecaoB() {
        return this.selecaoBySelecaoB;
    }
    
    public void setSelecaoBySelecaoB(Selecao selecaoBySelecaoB) {
        this.selecaoBySelecaoB = selecaoBySelecaoB;
    }
    public Selecao getSelecaoBySelecaoA() {
        return this.selecaoBySelecaoA;
    }
    
    public void setSelecaoBySelecaoA(Selecao selecaoBySelecaoA) {
        this.selecaoBySelecaoA = selecaoBySelecaoA;
    }
    public Escalacao getEscalacaoByEscalacaoB() {
        return this.escalacaoByEscalacaoB;
    }
    
    public void setEscalacaoByEscalacaoB(Escalacao escalacaoByEscalacaoB) {
        this.escalacaoByEscalacaoB = escalacaoByEscalacaoB;
    }
    public Escalacao getEscalacaoByEscalacaoA() {
        return this.escalacaoByEscalacaoA;
    }
    
    public void setEscalacaoByEscalacaoA(Escalacao escalacaoByEscalacaoA) {
        this.escalacaoByEscalacaoA = escalacaoByEscalacaoA;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }
    public Set getSubstituicaos() {
        return this.substituicaos;
    }
    
    public void setSubstituicaos(Set substituicaos) {
        this.substituicaos = substituicaos;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }




}


