package model.pojo;
// Generated 01/07/2014 12:52:27 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Jogo generated by hbm2java
 */
public class Jogo  implements java.io.Serializable {


     private Integer id;
     private Copa copa;
     private Selecao selecaoBySelecaoB;
     private Selecao selecaoBySelecaoA;
     private Date data;
     private String local;
     private String fase;
     private Set escalacaos = new HashSet(0);
     private Set substituicaos = new HashSet(0);
     private Set gols = new HashSet(0);

    public Jogo() {
    }

	
    public Jogo(Date data, String local, String fase) {
        this.data = data;
        this.local = local;
        this.fase = fase;
    }
    public Jogo(Copa copa, Selecao selecaoBySelecaoB, Selecao selecaoBySelecaoA, Date data, String local, String fase, Set escalacaos, Set substituicaos, Set gols) {
       this.copa = copa;
       this.selecaoBySelecaoB = selecaoBySelecaoB;
       this.selecaoBySelecaoA = selecaoBySelecaoA;
       this.data = data;
       this.local = local;
       this.fase = fase;
       this.escalacaos = escalacaos;
       this.substituicaos = substituicaos;
       this.gols = gols;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Copa getCopa() {
        return this.copa;
    }
    
    public void setCopa(Copa copa) {
        this.copa = copa;
    }
    public Selecao getSelecaoBySelecaoB() {
        return this.selecaoBySelecaoB;
    }
    
    public void setSelecaoBySelecaoB(Selecao selecaoBySelecaoB) {
        this.selecaoBySelecaoB = selecaoBySelecaoB;
    }
    public Selecao getSelecaoBySelecaoA() {
        return this.selecaoBySelecaoA;
    }
    
    public void setSelecaoBySelecaoA(Selecao selecaoBySelecaoA) {
        this.selecaoBySelecaoA = selecaoBySelecaoA;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }
    public Set getEscalacaos() {
        return this.escalacaos;
    }
    
    public void setEscalacaos(Set escalacaos) {
        this.escalacaos = escalacaos;
    }
    public Set getSubstituicaos() {
        return this.substituicaos;
    }
    
    public void setSubstituicaos(Set substituicaos) {
        this.substituicaos = substituicaos;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.copa);
        hash = 71 * hash + Objects.hashCode(this.selecaoBySelecaoB);
        hash = 71 * hash + Objects.hashCode(this.selecaoBySelecaoA);
        hash = 71 * hash + Objects.hashCode(this.data);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Jogo other = (Jogo) obj;
        if (!Objects.equals(this.copa, other.copa)) {
            return false;
        }
        if (!Objects.equals(this.selecaoBySelecaoB, other.selecaoBySelecaoB)) {
            return false;
        }
        if (!Objects.equals(this.selecaoBySelecaoA, other.selecaoBySelecaoA)) {
            return false;
        }
        if (!Objects.equals(this.data, other.data)) {
            return false;
        }
        return true;
    }




}


