package model.pojo;
// Generated 27/06/2014 16:47:37 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Selecao generated by hbm2java
 */
public class Selecao  implements java.io.Serializable {


     private Integer id;
     private Copa copa;
     private Pais pais;
     private Tecnico tecnico;
     private String grupo;
     private Date ano;
     private int posicao;
     private int jogador1;
     private int jogador2;
     private int jogador3;
     private int jogador5;
     private int jogador6;
     private int jogador7;
     private int jogador8;
     private int jogador9;
     private int jogador10;
     private int jogador11;
     private int jogador12;
     private int jogador13;
     private int jogador14;
     private int jogador15;
     private int jogador16;
     private int jogador17;
     private int jogador18;
     private int jogador19;
     private int jogador20;
     private int jogador21;
     private int jogador22;
     private int jogador23;
     private Set gols = new HashSet(0);
     private Set copas = new HashSet(0);
     private Set escalacaos = new HashSet(0);
     private Set substituicaos = new HashSet(0);
     private Set jogosForSelecaoB = new HashSet(0);
     private Set jogosForSelecaoA = new HashSet(0);

    public Selecao() {
    }
    public Selecao(Tecnico tecnico, String grupo, Date ano, int posicao, int jogador1, int jogador2, int jogador3, int jogador5, int jogador6, int jogador7, int jogador8, int jogador9, int jogador10, int jogador11, int jogador12, int jogador13, int jogador14, int jogador15, int jogador16, int jogador17, int jogador18, int jogador19, int jogador20, int jogador21, int jogador22, int jogador23) {
        this.tecnico = tecnico;
        this.grupo = grupo;
        this.ano = ano;
        this.posicao = posicao;
        this.jogador1 = jogador1;
        this.jogador2 = jogador2;
        this.jogador3 = jogador3;
        this.jogador5 = jogador5;
        this.jogador6 = jogador6;
        this.jogador7 = jogador7;
        this.jogador8 = jogador8;
        this.jogador9 = jogador9;
        this.jogador10 = jogador10;
        this.jogador11 = jogador11;
        this.jogador12 = jogador12;
        this.jogador13 = jogador13;
        this.jogador14 = jogador14;
        this.jogador15 = jogador15;
        this.jogador16 = jogador16;
        this.jogador17 = jogador17;
        this.jogador18 = jogador18;
        this.jogador19 = jogador19;
        this.jogador20 = jogador20;
        this.jogador21 = jogador21;
        this.jogador22 = jogador22;
        this.jogador23 = jogador23;
    }
    public Selecao(Copa copa, Pais pais, Tecnico tecnico, String grupo, Date ano, int posicao, int jogador1, int jogador2, int jogador3, int jogador5, int jogador6, int jogador7, int jogador8, int jogador9, int jogador10, int jogador11, int jogador12, int jogador13, int jogador14, int jogador15, int jogador16, int jogador17, int jogador18, int jogador19, int jogador20, int jogador21, int jogador22, int jogador23, Set gols, Set copas, Set escalacaos, Set substituicaos, Set jogosForSelecaoB, Set jogosForSelecaoA) {
       this.copa = copa;
       this.pais = pais;
       this.tecnico = tecnico;
       this.grupo = grupo;
       this.ano = ano;
       this.posicao = posicao;
       this.jogador1 = jogador1;
       this.jogador2 = jogador2;
       this.jogador3 = jogador3;
       this.jogador5 = jogador5;
       this.jogador6 = jogador6;
       this.jogador7 = jogador7;
       this.jogador8 = jogador8;
       this.jogador9 = jogador9;
       this.jogador10 = jogador10;
       this.jogador11 = jogador11;
       this.jogador12 = jogador12;
       this.jogador13 = jogador13;
       this.jogador14 = jogador14;
       this.jogador15 = jogador15;
       this.jogador16 = jogador16;
       this.jogador17 = jogador17;
       this.jogador18 = jogador18;
       this.jogador19 = jogador19;
       this.jogador20 = jogador20;
       this.jogador21 = jogador21;
       this.jogador22 = jogador22;
       this.jogador23 = jogador23;
       this.gols = gols;
       this.copas = copas;
       this.escalacaos = escalacaos;
       this.substituicaos = substituicaos;
       this.jogosForSelecaoB = jogosForSelecaoB;
       this.jogosForSelecaoA = jogosForSelecaoA;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Copa getCopa() {
        return this.copa;
    }
    
    public void setCopa(Copa copa) {
        this.copa = copa;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Tecnico getTecnico() {
        return this.tecnico;
    }
    
    public void setTecnico(Tecnico tecnico) {
        this.tecnico = tecnico;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }
    public int getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(int posicao) {
        this.posicao = posicao;
    }
    public int getJogador1() {
        return this.jogador1;
    }
    
    public void setJogador1(int jogador1) {
        this.jogador1 = jogador1;
    }
    public int getJogador2() {
        return this.jogador2;
    }
    
    public void setJogador2(int jogador2) {
        this.jogador2 = jogador2;
    }
    public int getJogador3() {
        return this.jogador3;
    }
    
    public void setJogador3(int jogador3) {
        this.jogador3 = jogador3;
    }
    public int getJogador5() {
        return this.jogador5;
    }
    
    public void setJogador5(int jogador5) {
        this.jogador5 = jogador5;
    }
    public int getJogador6() {
        return this.jogador6;
    }
    
    public void setJogador6(int jogador6) {
        this.jogador6 = jogador6;
    }
    public int getJogador7() {
        return this.jogador7;
    }
    
    public void setJogador7(int jogador7) {
        this.jogador7 = jogador7;
    }
    public int getJogador8() {
        return this.jogador8;
    }
    
    public void setJogador8(int jogador8) {
        this.jogador8 = jogador8;
    }
    public int getJogador9() {
        return this.jogador9;
    }
    
    public void setJogador9(int jogador9) {
        this.jogador9 = jogador9;
    }
    public int getJogador10() {
        return this.jogador10;
    }
    
    public void setJogador10(int jogador10) {
        this.jogador10 = jogador10;
    }
    public int getJogador11() {
        return this.jogador11;
    }
    
    public void setJogador11(int jogador11) {
        this.jogador11 = jogador11;
    }
    public int getJogador12() {
        return this.jogador12;
    }
    
    public void setJogador12(int jogador12) {
        this.jogador12 = jogador12;
    }
    public int getJogador13() {
        return this.jogador13;
    }
    
    public void setJogador13(int jogador13) {
        this.jogador13 = jogador13;
    }
    public int getJogador14() {
        return this.jogador14;
    }
    
    public void setJogador14(int jogador14) {
        this.jogador14 = jogador14;
    }
    public int getJogador15() {
        return this.jogador15;
    }
    
    public void setJogador15(int jogador15) {
        this.jogador15 = jogador15;
    }
    public int getJogador16() {
        return this.jogador16;
    }
    
    public void setJogador16(int jogador16) {
        this.jogador16 = jogador16;
    }
    public int getJogador17() {
        return this.jogador17;
    }
    
    public void setJogador17(int jogador17) {
        this.jogador17 = jogador17;
    }
    public int getJogador18() {
        return this.jogador18;
    }
    
    public void setJogador18(int jogador18) {
        this.jogador18 = jogador18;
    }
    public int getJogador19() {
        return this.jogador19;
    }
    
    public void setJogador19(int jogador19) {
        this.jogador19 = jogador19;
    }
    public int getJogador20() {
        return this.jogador20;
    }
    
    public void setJogador20(int jogador20) {
        this.jogador20 = jogador20;
    }
    public int getJogador21() {
        return this.jogador21;
    }
    
    public void setJogador21(int jogador21) {
        this.jogador21 = jogador21;
    }
    public int getJogador22() {
        return this.jogador22;
    }
    
    public void setJogador22(int jogador22) {
        this.jogador22 = jogador22;
    }
    public int getJogador23() {
        return this.jogador23;
    }
    
    public void setJogador23(int jogador23) {
        this.jogador23 = jogador23;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }
    public Set getCopas() {
        return this.copas;
    }
    
    public void setCopas(Set copas) {
        this.copas = copas;
    }
    public Set getEscalacaos() {
        return this.escalacaos;
    }
    
    public void setEscalacaos(Set escalacaos) {
        this.escalacaos = escalacaos;
    }
    public Set getSubstituicaos() {
        return this.substituicaos;
    }
    
    public void setSubstituicaos(Set substituicaos) {
        this.substituicaos = substituicaos;
    }
    public Set getJogosForSelecaoB() {
        return this.jogosForSelecaoB;
    }
    
    public void setJogosForSelecaoB(Set jogosForSelecaoB) {
        this.jogosForSelecaoB = jogosForSelecaoB;
    }
    public Set getJogosForSelecaoA() {
        return this.jogosForSelecaoA;
    }
    
    public void setJogosForSelecaoA(Set jogosForSelecaoA) {
        this.jogosForSelecaoA = jogosForSelecaoA;
    }




}


