package model.pojo;
// Generated 06/07/2014 15:27:33 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Selecao generated by hbm2java
 */
public class Selecao  implements java.io.Serializable {


     private Integer id;
     private Copa copa;
     private Pais pais;
     private Tecnico tecnico;
     private String grupo;
     private Date ano;
     private int posicao;
     private String nome;
     private Set jogadors = new HashSet(0);
     private Set jogosForSelecaoB = new HashSet(0);
     private Set gols = new HashSet(0);
     private Set jogosForSelecaoA = new HashSet(0);
     private Set substituicaos = new HashSet(0);
     private Set escalacaos = new HashSet(0);

    public Selecao() {
    }

	
    public Selecao(String grupo, Date ano, int posicao) {
        this.grupo = grupo;
        this.ano = ano;
        this.posicao = posicao;
    }
    public Selecao(Copa copa, Pais pais, Tecnico tecnico, String grupo, Date ano, int posicao, String nome, Set jogadors, Set jogosForSelecaoB, Set gols, Set jogosForSelecaoA, Set substituicaos, Set escalacaos) {
       this.copa = copa;
       this.pais = pais;
       this.tecnico = tecnico;
       this.grupo = grupo;
       this.ano = ano;
       this.posicao = posicao;
       this.nome = nome;
       this.jogadors = jogadors;
       this.jogosForSelecaoB = jogosForSelecaoB;
       this.gols = gols;
       this.jogosForSelecaoA = jogosForSelecaoA;
       this.substituicaos = substituicaos;
       this.escalacaos = escalacaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Copa getCopa() {
        return this.copa;
    }
    
    public void setCopa(Copa copa) {
        this.copa = copa;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Tecnico getTecnico() {
        return this.tecnico;
    }
    
    public void setTecnico(Tecnico tecnico) {
        this.tecnico = tecnico;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }
    public int getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(int posicao) {
        this.posicao = posicao;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getJogadors() {
        return this.jogadors;
    }
    
    public void setJogadors(Set jogadors) {
        this.jogadors = jogadors;
    }
    public Set getJogosForSelecaoB() {
        return this.jogosForSelecaoB;
    }
    
    public void setJogosForSelecaoB(Set jogosForSelecaoB) {
        this.jogosForSelecaoB = jogosForSelecaoB;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }
    public Set getJogosForSelecaoA() {
        return this.jogosForSelecaoA;
    }
    
    public void setJogosForSelecaoA(Set jogosForSelecaoA) {
        this.jogosForSelecaoA = jogosForSelecaoA;
    }
    public Set getSubstituicaos() {
        return this.substituicaos;
    }
    
    public void setSubstituicaos(Set substituicaos) {
        this.substituicaos = substituicaos;
    }
    public Set getEscalacaos() {
        return this.escalacaos;
    }
    
    public void setEscalacaos(Set escalacaos) {
        this.escalacaos = escalacaos;
    }


@Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + (this.id != null ? this.id.hashCode() : 0);
        hash = 37 * hash + (this.grupo != null ? this.grupo.hashCode() : 0);
        hash = 37 * hash + (this.ano != null ? this.ano.hashCode() : 0);
        hash = 37 * hash + this.posicao;
        hash = 37 * hash + (this.nome != null ? this.nome.hashCode() : 0);
        return hash;
    }


    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Selecao other = (Selecao) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.grupo, other.grupo)) {
            return false;
        }
        if (!Objects.equals(this.ano, other.ano)) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        if (this.posicao != other.posicao) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Selecao do(a) " + this.getNome() + " de " + this.getAno();
    }

}


