package model.pojo;
// Generated Jul 5, 2014 1:28:30 PM by Hibernate Tools 3.6.0


import java.sql.Time;
import java.util.Date;
import java.util.Objects;

/**
 * Substituicao generated by hbm2java
 */
public class Substituicao  implements java.io.Serializable {


     private Integer id;
     private Jogador jogadorByJogadorSai;
     private Selecao selecao;
     private Jogo jogo;
     private Jogador jogadorByJogadorEntra;
     private Time tempo;

    public Substituicao() {
    }

	
    public Substituicao(Time tempo) {
        this.tempo = tempo;
    }
    public Substituicao(Jogador jogadorByJogadorSai, Selecao selecao, Jogo jogo, Jogador jogadorByJogadorEntra, Time tempo) {
       this.jogadorByJogadorSai = jogadorByJogadorSai;
       this.selecao = selecao;
       this.jogo = jogo;
       this.jogadorByJogadorEntra = jogadorByJogadorEntra;
       this.tempo = tempo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jogador getJogadorByJogadorSai() {
        return this.jogadorByJogadorSai;
    }
    
    public void setJogadorByJogadorSai(Jogador jogadorByJogadorSai) {
        this.jogadorByJogadorSai = jogadorByJogadorSai;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Jogador getJogadorByJogadorEntra() {
        return this.jogadorByJogadorEntra;
    }
    
    public void setJogadorByJogadorEntra(Jogador jogadorByJogadorEntra) {
        this.jogadorByJogadorEntra = jogadorByJogadorEntra;
    }
    public Time getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Time tempo) {
        this.tempo = tempo;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.id);
        hash = 31 * hash + Objects.hashCode(this.jogadorByJogadorSai.getId());
        hash = 31 * hash + Objects.hashCode(this.jogo.getId());
        hash = 31 * hash + Objects.hashCode(this.jogadorByJogadorEntra.getId());
        hash = 31 * hash + Objects.hashCode(this.tempo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Substituicao other = (Substituicao) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.jogadorByJogadorSai.getId(), other.jogadorByJogadorSai.getId())) {
            return false;
        }
        if (!Objects.equals(this.jogo.getId(), other.jogo.getId())) {
            return false;
        }
        if (!Objects.equals(this.jogadorByJogadorEntra.getId(), other.jogadorByJogadorEntra.getId())) {
            return false;
        }
        if (!Objects.equals(this.tempo, other.tempo)) {
            return false;
        }
        return true;
    }




}


