package model.pojo;
// Generated 12/06/2014 11:49:37 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Gol generated by hbm2java
 */
public class Gol  implements java.io.Serializable {


     private int id;
     private Jogador jogador;
     private Selecao selecao;
     private Jogo jogo;
     private Date tempo;
     private boolean foiContra;

    public Gol() {
    }

    public Gol(int id, Jogador jogador, Selecao selecao, Jogo jogo, Date tempo, boolean foiContra) {
       this.id = id;
       this.jogador = jogador;
       this.selecao = selecao;
       this.jogo = jogo;
       this.tempo = tempo;
       this.foiContra = foiContra;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Date getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Date tempo) {
        this.tempo = tempo;
    }
    public boolean isFoiContra() {
        return this.foiContra;
    }
    
    public void setFoiContra(boolean foiContra) {
        this.foiContra = foiContra;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + this.id;
        hash = 29 * hash + (this.jogador != null ? this.jogador.hashCode() : 0);
        hash = 29 * hash + (this.selecao != null ? this.selecao.hashCode() : 0);
        hash = 29 * hash + (this.jogo != null ? this.jogo.hashCode() : 0);
        hash = 29 * hash + (this.tempo != null ? this.tempo.hashCode() : 0);
        hash = 29 * hash + (this.foiContra ? 1 : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Gol other = (Gol) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.jogador != other.jogador && (this.jogador == null || !this.jogador.equals(other.jogador))) {
            return false;
        }
        if (this.selecao != other.selecao && (this.selecao == null || !this.selecao.equals(other.selecao))) {
            return false;
        }
        if (this.jogo != other.jogo && (this.jogo == null || !this.jogo.equals(other.jogo))) {
            return false;
        }
        if (this.tempo != other.tempo && (this.tempo == null || !this.tempo.equals(other.tempo))) {
            return false;
        }
        if (this.foiContra != other.foiContra) {
            return false;
        }
        return true;
    }




}


