package model.pojo;
// Generated 12/06/2014 11:49:37 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jogo generated by hbm2java
 */
public class Jogo  implements java.io.Serializable {


     private int id;
     private Copa copa;
     private Date data;
     private String local;
     private String fase;
     private Set gols = new HashSet(0);
     private Set substituicaos = new HashSet(0);

    public Jogo() {
    }

	
    public Jogo(int id, Copa copa, Date data, String local, String fase) {
        this.id = id;
        this.copa = copa;
        this.data = data;
        this.local = local;
        this.fase = fase;
    }
    public Jogo(int id, Copa copa, Date data, String local, String fase, Set gols, Set substituicaos) {
       this.id = id;
       this.copa = copa;
       this.data = data;
       this.local = local;
       this.fase = fase;
       this.gols = gols;
       this.substituicaos = substituicaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Copa getCopa() {
        return this.copa;
    }
    
    public void setCopa(Copa copa) {
        this.copa = copa;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }
    public Set getSubstituicaos() {
        return this.substituicaos;
    }
    
    public void setSubstituicaos(Set substituicaos) {
        this.substituicaos = substituicaos;
    }




}


