package model.pojo;
// Generated 12/06/2014 11:49:37 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Selecao generated by hbm2java
 */
public class Selecao  implements java.io.Serializable {


     private int id;
     private Copa copa;
     private Pais pais;
     private String grupo;
     private Date ano;
     private int posicao;
     private Set tecnicos = new HashSet(0);
     private Set substituicaos = new HashSet(0);
     private Set gols = new HashSet(0);
     private Set copas = new HashSet(0);

    public Selecao() {
    }

	
    public Selecao(int id, Copa copa, Pais pais, String grupo, Date ano, int posicao) {
        this.id = id;
        this.copa = copa;
        this.pais = pais;
        this.grupo = grupo;
        this.ano = ano;
        this.posicao = posicao;
    }
    public Selecao(int id, Copa copa, Pais pais, String grupo, Date ano, int posicao, Set tecnicos, Set substituicaos, Set gols, Set copas) {
       this.id = id;
       this.copa = copa;
       this.pais = pais;
       this.grupo = grupo;
       this.ano = ano;
       this.posicao = posicao;
       this.tecnicos = tecnicos;
       this.substituicaos = substituicaos;
       this.gols = gols;
       this.copas = copas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Copa getCopa() {
        return this.copa;
    }
    
    public void setCopa(Copa copa) {
        this.copa = copa;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }
    public int getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(int posicao) {
        this.posicao = posicao;
    }
    public Set getTecnicos() {
        return this.tecnicos;
    }
    
    public void setTecnicos(Set tecnicos) {
        this.tecnicos = tecnicos;
    }
    public Set getSubstituicaos() {
        return this.substituicaos;
    }
    
    public void setSubstituicaos(Set substituicaos) {
        this.substituicaos = substituicaos;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }
    public Set getCopas() {
        return this.copas;
    }
    
    public void setCopas(Set copas) {
        this.copas = copas;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 67 * hash + this.id;
        hash = 67 * hash + (this.copa != null ? this.copa.hashCode() : 0);
        hash = 67 * hash + (this.pais != null ? this.pais.hashCode() : 0);
        hash = 67 * hash + (this.grupo != null ? this.grupo.hashCode() : 0);
        hash = 67 * hash + (this.ano != null ? this.ano.hashCode() : 0);
        hash = 67 * hash + this.posicao;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Selecao other = (Selecao) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.copa != other.copa && (this.copa == null || !this.copa.equals(other.copa))) {
            return false;
        }
        if (this.pais != other.pais && (this.pais == null || !this.pais.equals(other.pais))) {
            return false;
        }
        if ((this.grupo == null) ? (other.grupo != null) : !this.grupo.equals(other.grupo)) {
            return false;
        }
        if (this.ano != other.ano && (this.ano == null || !this.ano.equals(other.ano))) {
            return false;
        }
        if (this.posicao != other.posicao) {
            return false;
        }
        return true;
    }




}


