package model.pojo;
// Generated 12/06/2014 11:49:37 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Substituicao generated by hbm2java
 */
public class Substituicao  implements java.io.Serializable {


     private int id;
     private Selecao selecao;
     private Jogo jogo;
     private Date tempo;

    public Substituicao() {
    }

    public Substituicao(int id, Selecao selecao, Jogo jogo, Date tempo) {
       this.id = id;
       this.selecao = selecao;
       this.jogo = jogo;
       this.tempo = tempo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Date getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Date tempo) {
        this.tempo = tempo;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + this.id;
        hash = 79 * hash + (this.selecao != null ? this.selecao.hashCode() : 0);
        hash = 79 * hash + (this.jogo != null ? this.jogo.hashCode() : 0);
        hash = 79 * hash + (this.tempo != null ? this.tempo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Substituicao other = (Substituicao) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.selecao != other.selecao && (this.selecao == null || !this.selecao.equals(other.selecao))) {
            return false;
        }
        if (this.jogo != other.jogo && (this.jogo == null || !this.jogo.equals(other.jogo))) {
            return false;
        }
        if (this.tempo != other.tempo && (this.tempo == null || !this.tempo.equals(other.tempo))) {
            return false;
        }
        return true;
    }




}


