package model.Enunsd.NAOMEXER;
// Generated 03/06/2014 10:36:01 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jogador generated by hbm2java
 */
public class Jogador  implements java.io.Serializable {


     private int id;
     private Date dataNascimento;
     private String nome;
     private int numero;
     private String posicao;
     private Set gols = new HashSet(0);

    public Jogador() {
    }

	
    public Jogador(int id, Date dataNascimento, String nome, int numero, String posicao) {
        this.id = id;
        this.dataNascimento = dataNascimento;
        this.nome = nome;
        this.numero = numero;
        this.posicao = posicao;
    }
    public Jogador(int id, Date dataNascimento, String nome, int numero, String posicao, Set gols) {
       this.id = id;
       this.dataNascimento = dataNascimento;
       this.nome = nome;
       this.numero = numero;
       this.posicao = posicao;
       this.gols = gols;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }
    public Set getGols() {
        return this.gols;
    }
    
    public void setGols(Set gols) {
        this.gols = gols;
    }




}


