package model.Enunsd;
// Generated 03/06/2014 10:36:01 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Gol generated by hbm2java
 */
public class Gol  implements java.io.Serializable {


     private int id;
     private Jogador jogador;
     private Selecao selecao;
     private Jogo jogo;
     private Date tempo;
     private boolean foiContra;

    public Gol() {
    }

    public Gol(int id, Jogador jogador, Selecao selecao, Jogo jogo, Date tempo, boolean foiContra) {
       this.id = id;
       this.jogador = jogador;
       this.selecao = selecao;
       this.jogo = jogo;
       this.tempo = tempo;
       this.foiContra = foiContra;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Date getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Date tempo) {
        this.tempo = tempo;
    }
    public boolean isFoiContra() {
        return this.foiContra;
    }
    
    public void setFoiContra(boolean foiContra) {
        this.foiContra = foiContra;
    }




}


