package model.Enunsd;
// Generated 03/06/2014 10:36:01 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Substituicao generated by hbm2java
 */
public class Substituicao  implements java.io.Serializable {


     private int id;
     private Selecao selecao;
     private Jogo jogo;
     private Date tempo;

    public Substituicao() {
    }

    public Substituicao(int id, Selecao selecao, Jogo jogo, Date tempo) {
       this.id = id;
       this.selecao = selecao;
       this.jogo = jogo;
       this.tempo = tempo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    public Date getTempo() {
        return this.tempo;
    }
    
    public void setTempo(Date tempo) {
        this.tempo = tempo;
    }




}


