package model.Enunsd;
// Generated 03/06/2014 10:36:01 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tecnico generated by hbm2java
 */
public class Tecnico  implements java.io.Serializable {


     private int id;
     private Selecao selecao;
     private String nome;
     private Date dataNascimento;

    public Tecnico() {
    }

    public Tecnico(int id, Selecao selecao, String nome, Date dataNascimento) {
       this.id = id;
       this.selecao = selecao;
       this.nome = nome;
       this.dataNascimento = dataNascimento;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Selecao getSelecao() {
        return this.selecao;
    }
    
    public void setSelecao(Selecao selecao) {
        this.selecao = selecao;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }




}


